baseURL = 'http://example.org/'
languageCode = 'se-sv'
title = 'Turist'

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true


[params]
  homeText = "Reseanteckningar från det permanenta äventyret."

[permalinks]
  post = "/:filename/"